# Generated by Django 6.0.1 on 2026-01-16 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(choices=[('JARGON MARKET', 'JARGON MARKET'), ('EDITEURS / SOFTS / OUTILS', 'EDITEURS / SOFTS / OUTILS'), ('LANGAGES / FRAMEWORKS / BIBLIOTHEQUES', 'LANGAGES / FRAMEWORKS / BIBLIOTHEQUES'), ('BUISNESS MODEL', 'BUISNESS MODEL'), ('METRICS', 'METRICS')])),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Temps du quizz en minute')),
                ('require_score_to_pass', models.IntegerField(help_text='nombre de points minimum')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questions')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quizz'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quizz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
